spring:
  application:
    name: "umc9th"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL} # jdbc:mysql://localhost:3306/umc9th
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  token:
    secretKey: ZGh3YWlkc2F2ZXdhZXZ3b2EgMTM5ZXUgMDMxdWMyIHEyMiBAIDAgKTJFVio=
    expiration:
      access: 14400000 # 인증 정보 만료 시간